### ISSUE TITLE
Add this library to conda-forge recipes

### ISSUE THREAD

**Issue by ayushkamat** [andhus/dirhash-python#12]
Hello, I'm currently trying to upload a package that my company is writing to conda-forge, which depends on `dirhash`. It doesn't seem like this package is uploaded to conda-forge, so would it be possible to also host it there alongside PyPI? I'm more than happy to take care of it myself (all it involves is adding a .yaml file in the right place), but I wanted to run this by the maintainers here to see if this is something y'all would be okay with. Thanks!

**Comment by ba05** [comment]
Can you still do this?

**Comment by ba05** [comment]
Can't find this on conda-forge.
